### ISSUE TITLE
IsWon checks only columns and diagonals. How about rows?

### ISSUE THREAD

**Issue by Nickles255** [Nickles255/Game_Assignment6#1]
columns are down, rows are across.

Array notations for each location on the board
[0][0],  [1][0],  [2][0]
[0][1],  [1][1],  [2][1]
[0][2],  [1][2],  [2][2]

your matches are looking at the columns and diagonals
please add rows to the situation.

Have you looked into a looping mechanism for checking rows and columns? 
**Please attempt a for loop as shown yesterday in class. I can help debug it but you need to start the process.**

**Comment by kryptonianS** [comment]
re wrote the method.
