### ISSUE TITLE
isDraw method has incorrect output.

### ISSUE THREAD

**Issue by Nickles255** [Nickles255/Game_Assignment6#3]
please check win condition (isWon) in isDraw. Currently the logic just checks if the board is completely filled then the situation would be considered a draw.

This configuration below would be considered a draw in your current specifications
when this is not the case. 

--------------
| O | O | O |
--------------
| X | X | O |
--------------
| O | X | O |
--------------
isWin = true
isDraw = true

**Comment by Nickles255** [comment]
Please run TGB.java isDraw() is executing incorrectly. Please fix by Friday night.


Testing makeAMove for player1 and player 2

Enter a row for player X:
0
enter a column for player X:
1
--------------
|   | X |   |
--------------
|   |   |   |
--------------
|   |   |   |
--------------
Enter a row for player O:
1
enter a column for player O:
1
--------------
|   | X |   |
--------------
|   | O |   |
--------------
|   |   |   |
--------------

Testing isWon for X

false


--------------
| X | X | X |
--------------
| X | X | X |
--------------
| X | X | X |
--------------

Testing isDraw for draw situation.

true

Testing isWon for X

true
--------------
| X | X | X |
--------------
| X | X | X |
--------------
| X | X | X |
--------------

**Comment by kryptonianS** [comment]
In the isDraw method I re wrote the code like this:
draw==false
 for(int row = 0; row<board.length;row++){
            for(int col = 0;col<board[row].length;col++){
                if(board[row][col]!=' '&&isWon('x')==draw&&isWon('o')){
                   draw== true;               
                }
                
            }
        }
    
        return draw;

I tested the code on the TBG.java and it doesnt return true( is a draw) when the board is filled up and there is a 3 in a row match.

**Comment by kryptonianS** [comment]
hey ken, so i think i just figured out the code. I tested on TGB.java and
it works. it returned false(meaning not draw) even though the board is full
and there is a 3 in a row match.  It returned true(its a draw) when there
is no match and the board is full.
I posted on gitHUB. let me know if there is still any issue to be address
on this new code.
thank you

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Nickles255** [comment]
Just tested it and it looks like it works. When I put in uppercase letters like I originally had in the test it does not work. Please change how iswon(char) takes in an argument so it doesn't matter if X or x and O or o is put in.

**Comment by Nickles255** [comment]
Hi QD your code is not doing the right thing. you need to do a trace figure out what your code is actually doing.

--------------
| o |   |   |
--------------
|   | o |   |
--------------
|   |   | o |
--------------

Testing isDraw for draw situation.

true

Testing isWon for X

false
--------------
| o |   |   |
--------------
|   | o |   |
--------------
|   |   | o |
--------------

**Comment by kryptonianS** [comment]
okay I re wrote the code and tested all possible setting and it works.
below is few of the output i took from my IDE after testing it.
oh and Ken, I'll fix the upperLowercase issue on the isWon() method later today.  
Hopefully this is the right logic code. 

Testing makeAMove for player1 and player 2



--------------
| X | X | X | 
--------------
| X | X | X | 
--------------
| X | X | X | 
--------------

Testing isDraw for draw situation.

false

Testing isWon for O 

false
--------------
| X | X | X | 
--------------
| X | X | X | 
--------------
| X | X | X | 
--------------

Testing isWon for X 

true
--------------
| X | X | X | 
--------------
| X | X | X | 
--------------
| X | X | X| 
--------------
BUILD SUCCESSFUL (total time: 0 seconds)

------- Testing for Phase 2 Methods in Gameboard--------

Testing makeAMove for player1 and player 2



--------------
|   | X |   | 
--------------
|   | X |   | 
--------------
|   | X |   | 
--------------

Testing isDraw for draw situation.

false

Testing isWon for O 

false
--------------
|   | X |   | 
--------------
|   | X |   | 
--------------
|   | X |   | 
--------------

Testing isWon for X 

true
--------------
|   | X |   | 
--------------
|   | X |   | 
--------------
|   | X |   | 
--------------
BUILD SUCCESSFUL (total time: 0 seconds)



------- Testing for Phase 2 Methods in Gameboard--------

Testing makeAMove for player1 and player 2



--------------
|   |   |   | 
--------------
|   | X |   | 
--------------
|   |   |   | 
--------------

Testing isDraw for draw situation.

false

Testing isWon for O 

false
--------------
|   |   |   | 
--------------
|   | X |   | 
--------------
|   |   |   | 
--------------

Testing isWon for X 

false
--------------
|   |   |   | 
--------------
|   | X |   | 
--------------
|   |   |   | 
--------------
BUILD SUCCESSFUL (total time: 0 seconds)

**Comment by Nickles255** [comment]
I tested code today morning and it is not working correctly. Here is my output. I have rewritten TGB so it shows all these test cases when you run it. 

You need to think of all cases you should be testing for. As we messaged about, a tie is based on 
      1. full board 
      2. three in a row.

You need to create at least 4 test cases based on our discussion. 

1. Full board three in a row 
2. Full board no three in a row
3. Not full board three in a row
4. Not full board no three in a row.

In each of these cases isWin and isDraw should be producing the right output.
Second case, which is the definition of a draw, contains incorrect output. Please confirm at least these 4 cases are correct before confirming code is complete.

Writing more code is not the solution. If you do a trace you might be able to see why it is incorrect. Then figure out how you can correct your bug.

--------------
| X | X | X |
--------------
| X | X | X |
--------------
| X | X | X |
--------------

Testing isDraw for draw situation.

false

Testing isWon for X

true


--------------
| O | O | X |
--------------
| X | O | O |
--------------
| O | X | X |
--------------

Testing isDraw for draw situation.

false

Testing isWon for X

false


--------------
|   |   |   |
--------------
|   |   | O |
--------------
| O | X | X |
--------------

Testing isDraw for draw situation.

false

Testing isWon for X

false


--------------
|   | O | O |
--------------
|   |   | O |
--------------
| X | X | X |
--------------

Testing isDraw for draw situation.

false

Testing isWon for X

true

**Comment by kryptonianS** [comment]
I  added a local variable called space in the method to store the result of the board for each cell that is checked by the for loop. This variable determines if the board is full or not. which is one of the condition along with the isWon() condition to determine if there is a draw or not.

I tested it and its working correctly.
 This is my result from testing on 4 settings:
run:

------- Testing for Phase 2 Methods in Gameboard--------



--------------
| X | X | X | 
--------------
| X | X | X | 
--------------
| X | X | X | 
--------------

Testing isDraw for draw situation.

false

Testing isWon for X 

true

Testing isWon for O 

false


--------------
| O | O | X | 
--------------
| X | O | O | 
--------------
| O | X | X | 
--------------

Testing isDraw for draw situation.

true

Testing isWon for X 

false

Testing isWon for O 

false


--------------
|   |   |   | 
--------------
|   |   | O | 
--------------
| O | X | X | 
--------------

Testing isDraw for draw situation.

false

Testing isWon for X 

false

Testing isWon for O 

false


--------------
|   | O | O | 
--------------
|   |   | X | 
--------------
| O | O | O | 
--------------

Testing isDraw for draw situation.

false

Testing isWon for X 

false

Testing isWon for O 

true
BUILD SUCCESSFUL (total time: 0 seconds) 

Based on the output:
 1.when board is full and there is no win;  it's a draw(true).

2.When there is an empty cell and there is no win;   it's not draw.

3.when there is an 3 in a row and board not full and there is a win;  it's not draw. 

4. When there is a full board and there is a win; it's not draw.
