### ISSUE TITLE
Please do not add a beta file

### ISSUE THREAD

**Issue by Nickles255** [Nickles255/Game_Assignment6#4]
Your whole branch is beta. When the Gameboard.java program meets our specifications I will merge the code back into our master branch. This is the whole purpose of git. 
Creating a separate file makes this task harder when I need to merge.

If you need a beta file, keep it in a separate folder.

I usually have two folders one which is the main project and one which I am conducting beta work as I am testing out solutions to the assignment.  
**m-(/cygdrive/c/users/acer/dropbox/git)-(17 files, 105Kb)--> ls -la |grep Assignment6
drwxr-xr-x+ 1 Acer Acer    0 Nov  1 05:18 Assignment6_clin
drwxr-xr-x+ 1 Acer Acer    0 Oct 29 21:01 Game_Assignment6**

**Comment by kryptonianS** [comment]
removed the beta file
