### ISSUE TITLE
Please fix spacing in all your methods.

### ISSUE THREAD

**Issue by Nickles255** [Nickles255/Game_Assignment6#5]
Hi QD please review your code and fix spacing.
JustAsICanWriteASentence Like ThisAndYouCouldProbabilyReadIt.

It would be easier if I put spaces between my words. Your code is inconsistent sometimes you put a space and sometimes you don't. Please read over your code to ensure the next person examining it will have an easy experience.

//sometimes contains a space between + and sometimes doesn't.
  System.out.println("enter a column for player" +" "+ player+":"); 

//sometimes contains a space after == and sometimes doesn't
 if(isWon('x')== false && isWon('o')==false){
            for(int row = 0; row<board.length;row++){   

//consistent but may be hard to read.
if(board[2][0]==player&&board[1][1]==player&&board[0][2]==player)

**Comment by Nickles255** [comment]
![image](https://user-images.githubusercontent.com/4764414/32375997-b22f9574-c060-11e7-837c-66b8956e159e.png)

**Comment by Nickles255** [comment]
As a side note please use your text editors to check for spacing and Tab. Try to eliminate them so Lena doesn't always have to fix our spacing issues.

**Comment by kryptonianS** [comment]
I went through all the spaces and fixed them
