### ISSUE TITLE
isDraw is ending the game too early

### ISSUE THREAD

**Issue by thisfinalcode** [Nickles255/Game_Assignment6#6]
The isDraw method is ending the game prematurely:
in this situation, it had ended the game:
Enter a row for player O:
1
Enter a column for player O:
0
--------------
| O | X |   |
--------------
| O | X |   |
--------------
|   |   |   |
--------------
Enter a row for player X:
0
Enter a column for player X:
2
This game is a draw
--------------
| O | X | X |
--------------
| O | X |   |
--------------
|   |   |   |
--------------

**Comment by lzhengem** [comment]
the if statement is inside of the outter loop, when it should be outside of it:
`     public  boolean isDraw(){
        //Create a local variable to 
        //represent the current status of cell in the board
        int Space = 0;
        //set a boolean 
        boolean draw = false;
        //loop through the board to check for occupied space
        for(int row=0; row<board.length; row++){
            for(int col=0;col<board[row].length; col++){
                //if a cell in the board is empty
                //Store the information on Space and increment to the next Space
                if(board[row][col] == ' '){
                Space++;    
                }
            }
        }
        //if the all space is occupiedboard and there is no winner then it's a draw
        if(Space == 0 && isWon('X') == false && isWon('O') == false){
            draw = true;
        }
        return draw;
    }`

**Comment by thisfinalcode** [comment]
the second if statement should be outside of the loop
`    public  boolean isDraw(){
        //Create a local variable to 
        //represent the current status of cell in the board
        int Space = 0;
        //set a boolean 
        boolean draw = false;
        //loop through the board to check for occupied space
        for(int row=0; row<board.length; row++){
            for(int col=0;col<board[row].length; col++){
                //if a cell in the board is empty
                //Store the information on Space and increment to the next Space
                if(board[row][col] == ' '){
                Space++;    
                }
            }
        }
        //if the all space is occupiedboard and there is no winner then it's a draw
        if(Space == 0 && isWon('X') == false && isWon('O') == false){
            draw = true;
        }
        return draw;
    }`

**Comment by kryptonianS** [comment]
I moved the if statement according to what Lena stated on the error.
so now i have re- tested and it should now be giving out correct output.
this is my output after putting the if statement outside of the outter for loop:

--------------
| O | X | X | 
--------------
| O | X |   | 
--------------
|   |   |   | 
--------------

Testing isDraw for draw situation.

false

Testing isWon for X 

false

Testing isWon for O 

false


--------------
| O | O | X | 
--------------
| X | O | O | 
--------------
| O | X | X | 
--------------

Testing isDraw for draw situation.

true

Testing isWon for X 

false

Testing isWon for O 

false


--------------
|   |   |   | 
--------------
|   |   | O | 
--------------
| O | X | X | 
--------------

Testing isDraw for draw situation.

false

Testing isWon for X 

false

Testing isWon for O 

false


--------------
|   | O | O | 
--------------
|   |   | X | 
--------------
| O | O | O | 
--------------

Testing isDraw for draw situation.

false

Testing isWon for X 

false

Testing isWon for O 

true
BUILD SUCCESSFUL (total time: 0 seconds)
