### ISSUE TITLE
Going into testing Phase.

### ISSUE THREAD

**Issue by Nickles255** [Nickles255/Game_Assignment6#7]
Thanks Lena for catching our bug and getting your part up so quickly. I have merged everything into masters. Everyone please perform some testing and provide feedback on anything bugs or spacing errors you detect.

Thank you

Ken

**Comment by Nickles255** [comment]
Performed my testing
Code:
  removed java.utils.array = not used
  modified makeAMove to shorten System.out.println statements
  checked spacing. no trailing spaces after statements.

GamePlay: 
   Made suggestion after play 3 or four games with differing outcomes.

**Comment by kryptonianS** [comment]
i have tested the game 10 times with all possible setting. 
no bugs found. Everything works correctly.

**Comment by Nickles255** [comment]
Testing complete and file is Zipped. 4 files in Zip gameboard.java, tictactoe.java and corresponding classes.
File is ready to submit.
