### ISSUE TITLE
Slight adjustments to output.

### ISSUE THREAD

**Issue by Nickles255** [Nickles255/Game_Assignment6#8]
Hi Lena and QD, could we make the output look like the results from the instructor's example.
Hers saves space on the screen and the winning statement at the end appears more final.
modification needs to be made in makeAMove and TicTacToe.java.

These are minor changes. Please just make them in master.

Current output:
![image](https://user-images.githubusercontent.com/4764414/32416731-d13d0d9a-c202-11e7-9894-6dc1071ecd0d.png)

Instructors output:
![image](https://user-images.githubusercontent.com/4764414/32416749-3423e514-c203-11e7-9828-77cbf99e14fa.png)

**Comment by thisfinalcode** [comment]
Okay, changed it in TicTacToe to make the output more "final"

![image](https://user-images.githubusercontent.com/7026683/32426647-c18f160e-c270-11e7-9012-77f31b97c823.png)

**Comment by Nickles255** [comment]
Modified makeAmove from println to print. Also added some spacing to both TicTacToe.java and Gameboard.java print portions to make output pretty.

![image](https://user-images.githubusercontent.com/4764414/32476357-a9d27a7c-c32b-11e7-9b6c-003b7b8b55fd.png)

**Comment by kryptonianS** [comment]
awesome ken

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
